### PR TITLE
Fix build error on darwin

### PR DESCRIPTION
**Pull request by mpppk**
Build on darwin fails due to missing the change in #22.

```sh
$ sw_vers
ProductName:    macOS
ProductVersion: 11.2.1
BuildVersion:   20D74

$ go build ./...
./file_darwin.go:99:16: undefined: ret
```

This PR fix the build error and now I confirmed that the build will pass.

### CODE REVIEW

**Comment by gen2brain** [comment]
Thanks!
